language: php
php:
  - "7.2-alpine"

services:
  - docker

before_script:
- docker pull vonp/back-terraqueus-php
- docker pull vonp/back-terraqueus-node

script:
- composer install
- npm install
- npm start
