version: "3"

services:

    php:
        container_name: ${APP_NAME}-php
        build: php
        user: www-data
        working_dir: ${SYMFONY_DOCKER_PATH}
        volumes:
            - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
            - ./php/php.ini:/usr/local/etc/php/php.ini
        env_file:
          - ${ENV_FILE_DIR}

    nginx:
        container_name: ${APP_NAME}-nginx
        build: nginx
        ports:
            - ${NGINX_PORT_EXPOSE}:${NGINX_PORT}
        links:
            - php
        volumes:
            - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
        env_file:
          - ${ENV_FILE_DIR}

    node:
        container_name: ${APP_NAME}-node
        build: node
        user: node
        working_dir: ${SYMFONY_DOCKER_PATH}
        volumes:
            - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
        env_file:
          - ${ENV_FILE_DIR}
        command: sh -c "npm install && npm start"

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:4-alpine
        ports:
            - ${REDIS_PORT_EXPOSE}:${REDIS_PORT}
